"""
Recommendation Model
=====================
Stores pre-computed job recommendations generated by the recommendation engine.

Maps to: RECOMMENDATIONS table in the ER diagram.

Design Decisions:
- Recommendations are pre-computed and stored rather than computed on-the-fly.
  This provides fast dashboard loading and allows historical tracking.
- Each recommendation includes:
  * overall_score: The final Job Fit Score
  * Component scores: skill_score, experience_score, education_score
  * score_breakdown: Detailed JSON with cosine similarity, KNN distance, etc.
  * strengths: JSON array of candidate's strong points for this job
  * improvements: JSON array of areas where the candidate could improve
- Recommendations are regenerated when:
  1. A candidate uploads/updates their resume
  2. New jobs are posted
  3. Admin triggers a system-wide recomputation
- The strengths/improvements fields implement the proposal requirement
  (Section 3.2.4) for providing feedback on candidate profiles.
"""

from datetime import datetime, timezone
from app.extensions import db


class Recommendation(db.Model):
    """
    Pre-computed job recommendation for a candidate.

    Generated by the recommendation engine using the candidate's active
    resume matched against available job postings. Includes both numerical
    scores and human-readable feedback.
    """

    __tablename__ = 'recommendations'

    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(
        db.Integer,
        db.ForeignKey('candidates.id', ondelete='CASCADE'),
        nullable=False,
        index=True
    )
    job_id = db.Column(
        db.Integer,
        db.ForeignKey('jobs.id', ondelete='CASCADE'),
        nullable=False,
        index=True
    )
    resume_id = db.Column(
        db.Integer,
        db.ForeignKey('resumes.id', ondelete='SET NULL'),
        nullable=True
    )

    # Scores (all normalized to 0.0 - 1.0 range)
    overall_score = db.Column(db.Float, nullable=False)  # Final Job Fit Score
    skill_score = db.Column(db.Float)      # Weighted Jaccard similarity of skills
    experience_score = db.Column(db.Float)  # Experience years/level match
    education_score = db.Column(db.Float)   # Education level match

    # Detailed breakdown (cosine sim, KNN distance, component weights, etc.)
    score_breakdown = db.Column(db.JSON)

    # Human-readable feedback (proposal Section 3.2.4)
    strengths = db.Column(db.JSON)      # e.g., ["Strong Python skills", "Relevant degree"]
    improvements = db.Column(db.JSON)   # e.g., ["Consider learning Docker", "More experience needed"]

    # Timestamp
    generated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # Prevent duplicate recommendations per candidate-job pair
    __table_args__ = (
        db.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job_recommendation'),
    )

    @property
    def score_percentage(self):
        """Returns overall score as a percentage."""
        return f'{self.overall_score * 100:.1f}%'

    @property
    def score_label(self):
        """Returns a human-readable label for the score range."""
        if self.overall_score >= 0.8:
            return 'Excellent Match'
        elif self.overall_score >= 0.6:
            return 'Good Match'
        elif self.overall_score >= 0.4:
            return 'Fair Match'
        else:
            return 'Low Match'

    def __repr__(self):
        return f'<Recommendation candidate={self.candidate_id} job={self.job_id} score={self.overall_score:.2f}>'
